spring.application.name=sms-journey-service

spring.datasource.url=jdbc:postgresql://localhost:5432/sms_journey
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
management.endpoints.web.exposure.include=health,info

#pagination
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

#kafka
spring.kafka.bootstrap-servers=localhost:9092

# Key is a basic String
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Value is Jackson JSON (Replaces the deprecated JsonSerializer)
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer



spring.kafka.consumer.group-id=sms-journey-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

app.kafka.bootstrap-servers=localhost:9092
app.kafka.sms-topic=sms-journey-topic
app.kafka.sms-group-id=sms-journey-group


#cache
sms-journey.cache.expire-after-write=10m
